SELECT
	DISTINCT su.USER_LOGIN,
	css.CSTS_DESCRIPTION,
	css.CSTS_LONG_DESCRIPTION,
	spr.USRO_FAVOURITE
FROM
	ORMA_PROFESSIONALS op
INNER JOIN SECU_USERS su ON
	op.PROF_ID = su.PROF_ID
INNER JOIN SECU_PROF_ROLE_ACTIONS spra ON
	op.PROF_ID = spra.PROF_ID
INNER JOIN SECU_PROFESSIONAL_ROLES spr ON
	op.PROF_ID = spr.PROF_ID
INNER JOIN CONF_ACTIONS ca ON
	spra.SIAC_ID = ca.SIAC_ID
INNER JOIN CONF_STATION_STRUCTURES css ON
	ca.SIAC_ID = css.SIAC_ID
WHERE
	su.USER_LOGIN = 'abernal'
	AND spr.USRO_FAVOURITE = TRUE